# separated from the Tiobe workflow to prevent building/running
# untrusted code within the repo, e.g. running `go test` in
# pull_request_target

# completion of this workflow triggers the tiobe workflow, which
# executes with access to secrets, but does NOT run the code 
# associated with the pull request

name: Coverage
on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Test TICS daily

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Setup dependencies
        run: |
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Test
        run: |
          go test -v -p 1 -coverprofile=coverage.out ./...

      - name: Convert coverage files
        run: |
          mkdir -p cover
          gocov convert coverage.out > cover/coverage.json
          gocov-xml < cover/coverage.json > cover/coverage-go.xml

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: coverage
          path: cover/
