name: Tiobe TICS
on:
  workflow_run:
    workflows: ["Coverage"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  tics:
    name: Tiobe TICS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  # v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage
          path: cover/

      - name: Run TiCS client analysis
        uses: tiobe/tics-github-action@v3
        if: github.event_name == 'pull_request_target'
        with:
          mode: client
          project: starlark
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          calc: ALL

      - name: Run TiCS server analysis
        uses: tiobe/tics-github-action@v3
        if: github.event_name != 'pull_request_target'
        with:
          mode: qserver
          project: starlark
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          calc: ALL
