// Code generated by "stringer -type=SafetyFlags"; DO NOT EDIT.

package starlark

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CPUSafe-1]
	_ = x[IOSafe-2]
	_ = x[MemSafe-4]
	_ = x[TimeSafe-8]
	_ = x[safetyFlagsLimit-16]
}

const (
	_SafetyFlags_name_0 = "CPUSafeIOSafe"
	_SafetyFlags_name_1 = "MemSafe"
	_SafetyFlags_name_2 = "TimeSafe"
	_SafetyFlags_name_3 = "safetyFlagsLimit"
)

var (
	_SafetyFlags_index_0 = [...]uint8{0, 7, 13}
)

func (i SafetyFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _SafetyFlags_name_0[_SafetyFlags_index_0[i]:_SafetyFlags_index_0[i+1]]
	case i == 4:
		return _SafetyFlags_name_1
	case i == 8:
		return _SafetyFlags_name_2
	case i == 16:
		return _SafetyFlags_name_3
	default:
		return "SafetyFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
